version: '3.8'

services:
  app:
    build: .
    container_name: shopping_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:IHMSwzUFPWfcEkFZjCTWLjvesUzsgdpu@crossover.proxy.rlwy.net:53246/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: IHMSwzUFPWfcEkFZjCTWLjvesUzsgdpu
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"

